name: foam-vit
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.8
  - torchvision
  - pytorch-cuda=12.8
  - numpy
  - pillow
  - pyyaml
  - pip
  - pip:
      - timm
      - pytest
      - matplotlib
      - wandb
      - datasets
